var annotated_dup =
[
    [ "AggregatedOptions", "structAggregatedOptions.html", "structAggregatedOptions" ],
    [ "CHARACTER", "structCHARACTER.html", "structCHARACTER" ],
    [ "CLASS", "structCLASS.html", "structCLASS" ],
    [ "ContextMenuBuilder", "structContextMenuBuilder.html", "structContextMenuBuilder" ],
    [ "ENTITY", "structENTITY.html", "structENTITY" ],
    [ "FACTION", "structFACTION.html", "structFACTION" ],
    [ "FrameworkZ", "structFrameworkZ.html", "structFrameworkZ" ],
    [ "INVENTORY", "structINVENTORY.html", "structINVENTORY" ],
    [ "ITEM", "structITEM.html", "structITEM" ],
    [ "MenuManager", "structMenuManager.html", "structMenuManager" ],
    [ "Options", "structOptions.html", "structOptions" ],
    [ "PFW_CharacterPreview", "structPFW__CharacterPreview.html", "structPFW__CharacterPreview" ],
    [ "PFW_CharacterView", "structPFW__CharacterView.html", "structPFW__CharacterView" ],
    [ "PFW_CreateCharacterAppearance", "structPFW__CreateCharacterAppearance.html", "structPFW__CreateCharacterAppearance" ],
    [ "PFW_CreateCharacterFaction", "structPFW__CreateCharacterFaction.html", "structPFW__CreateCharacterFaction" ],
    [ "PFW_CreateCharacterInfo", "structPFW__CreateCharacterInfo.html", "structPFW__CreateCharacterInfo" ],
    [ "PFW_Introduction", "structPFW__Introduction.html", "structPFW__Introduction" ],
    [ "PFW_LoadCharacterMenu", "structPFW__LoadCharacterMenu.html", "structPFW__LoadCharacterMenu" ],
    [ "PFW_MainMenu", "structPFW__MainMenu.html", "structPFW__MainMenu" ],
    [ "PFW_Notification", "structPFW__Notification.html", "structPFW__Notification" ],
    [ "PLAYER", "structPLAYER.html", "structPLAYER" ],
    [ "SUBCLASS", "structSUBCLASS.html", "structSUBCLASS" ],
    [ "UI", "structUI.html", "structUI" ]
];